### ISSUE TITLE
Naming of fields

### ISSUE THREAD

**Issue by h4cc** [decentlab/decentlab-decoders#1]
Using field names with spaces will lead to problems using filter/rules and other ELEMENT-IOT features. Typically we try to name fields like `pressure` or `battery_voltage`.

https://github.com/decentlab/decentlab-decoders/blob/a6f1c82f216e3b085a0bf450cf0a948e6fa5b750/LoRaWAN%20Pressure%20(Depth)%20and%20Temperature%20Sensor/DL-PR26D%20(Pmin%3D0.0%2C%20Pmax%3D1.0).ELEMENT-IoT.ex#L15

Our implementation for reference: https://github.com/ZennerIoT/element-parsers/blob/master/lib/decentlab_dl_pr26.ex

**Comment by decentlab** [comment]
Can field names be atoms like `:sensor0value1`, `:sensor1value1`, etc? Are they visible to the end users?

**Comment by h4cc** [comment]
Fields can be atoms or strings. atoms will be converted to string anyhow. Its easier to write elixir maps using atoms.

Fields are visible to the user. If a human readable name should be shown, the "display" value will be used if available.

The fields are used in filter/rules/exports. Having spaces in them is possible, but will compilcate simple filters like `battery_voltage < 3`.

It is possible to return a list of readings for a single `parse/2`call. So instead of naming like `sensor0: value0, sensor1: value1`, there can be two readings created with `sensor: 0, value: value0` and `sensor: 1, value: value1`.

**Comment by decentlab** [comment]
The fields have been renamed as advised with 15e0c7e. Feel free to reopen if necessary.
